all:json.o libjson.so libjson.a

CC=gcc

CFLAGS= -g
	
json.o:
	$(CC) $(CFLAGS) -fpic -c $(@:o=c) -o $@

jsona.o:
	$(CC) $(CFLAGS) -c $(@:o=c) -o $@

libjson.so:
	$(CC) $(CFLAGS) -shared -o $@ json.o
	
libjson.a:
	ar -rcs $@ json.o

.PHONY:clean
clean:
	@rm -rf *.o *.so *.a